version: '3.2'

services:
  httpd:
    image: custom-httpd
    build: .
    ports:
      - '8080:80'
    volumes:
      - type: bind
        source: ./www
        target: /var/www
      - type: bind
        source: ./000-default.conf
        target: /etc/apache2/sites-enabled/000-default.conf

  mysql:
    image: mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysqlSlim:/var/lib/mysql
      #- ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      #MYSQL_DATABASE: 'phpdb'
      #MYSQL_USER: 'user'
      #MYSQL_PASSWORD: 'pass'

volumes:
  mysqlSlim:

